### ISSUE TITLE
New Feature: Seasons 

### ISSUE THREAD

**Issue by krichly** [klauck/kicker#3]
Can we add seasons? After several hundred games the number of position changes converges to zero.  Seasons could improve the long-time motivation.

**Comment by klauck** [comment]
Yes.

My proposal:
We add a `Season` class with a `begin` and `end` field.
Seasons can then be added and modified in the admin.

The main page shows the current season (and links to former seasons and overall ratings).

**Comment by klauck** [comment]
Done.
